// flow-typed signature: 48b5a7296355ea91b0bf54322322536e
// flow-typed version: <<STUB>>/webpackbar_v^3.2.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpackbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpackbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpackbar/dist/cjs' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/index' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/plugin' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/profiler/description' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/profiler/format' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/profiler/index' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/reporters/basic' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/reporters/fancy' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/reporters/index' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/reporters/profile' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/reporters/stats' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/utils/cli' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/utils/consts' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/utils/index' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/utils/log-update' {
  declare module.exports: any;
}

declare module 'webpackbar/dist/utils/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpackbar/dist/cjs.js' {
  declare module.exports: $Exports<'webpackbar/dist/cjs'>;
}
declare module 'webpackbar/dist/index.js' {
  declare module.exports: $Exports<'webpackbar/dist/index'>;
}
declare module 'webpackbar/dist/plugin.js' {
  declare module.exports: $Exports<'webpackbar/dist/plugin'>;
}
declare module 'webpackbar/dist/profiler/description.js' {
  declare module.exports: $Exports<'webpackbar/dist/profiler/description'>;
}
declare module 'webpackbar/dist/profiler/format.js' {
  declare module.exports: $Exports<'webpackbar/dist/profiler/format'>;
}
declare module 'webpackbar/dist/profiler/index.js' {
  declare module.exports: $Exports<'webpackbar/dist/profiler/index'>;
}
declare module 'webpackbar/dist/reporters/basic.js' {
  declare module.exports: $Exports<'webpackbar/dist/reporters/basic'>;
}
declare module 'webpackbar/dist/reporters/fancy.js' {
  declare module.exports: $Exports<'webpackbar/dist/reporters/fancy'>;
}
declare module 'webpackbar/dist/reporters/index.js' {
  declare module.exports: $Exports<'webpackbar/dist/reporters/index'>;
}
declare module 'webpackbar/dist/reporters/profile.js' {
  declare module.exports: $Exports<'webpackbar/dist/reporters/profile'>;
}
declare module 'webpackbar/dist/reporters/stats.js' {
  declare module.exports: $Exports<'webpackbar/dist/reporters/stats'>;
}
declare module 'webpackbar/dist/utils/cli.js' {
  declare module.exports: $Exports<'webpackbar/dist/utils/cli'>;
}
declare module 'webpackbar/dist/utils/consts.js' {
  declare module.exports: $Exports<'webpackbar/dist/utils/consts'>;
}
declare module 'webpackbar/dist/utils/index.js' {
  declare module.exports: $Exports<'webpackbar/dist/utils/index'>;
}
declare module 'webpackbar/dist/utils/log-update.js' {
  declare module.exports: $Exports<'webpackbar/dist/utils/log-update'>;
}
declare module 'webpackbar/dist/utils/webpack.js' {
  declare module.exports: $Exports<'webpackbar/dist/utils/webpack'>;
}
