// flow-typed signature: f5694952fc881076b2054f2c515d0e9a
// flow-typed version: <<STUB>>/@fullhuman/postcss-purgecss_v^1.2.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fullhuman/postcss-purgecss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fullhuman/postcss-purgecss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fullhuman/postcss-purgecss/__tests__/fixtures/src/config/config' {
  declare module.exports: any;
}

declare module '@fullhuman/postcss-purgecss/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@fullhuman/postcss-purgecss/jest.config' {
  declare module.exports: any;
}

declare module '@fullhuman/postcss-purgecss/lib/postcss-purgecss.es' {
  declare module.exports: any;
}

declare module '@fullhuman/postcss-purgecss/lib/postcss-purgecss' {
  declare module.exports: any;
}

declare module '@fullhuman/postcss-purgecss/rollup.config' {
  declare module.exports: any;
}

declare module '@fullhuman/postcss-purgecss/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fullhuman/postcss-purgecss/__tests__/fixtures/src/config/config.js' {
  declare module.exports: $Exports<'@fullhuman/postcss-purgecss/__tests__/fixtures/src/config/config'>;
}
declare module '@fullhuman/postcss-purgecss/__tests__/index.test.js' {
  declare module.exports: $Exports<'@fullhuman/postcss-purgecss/__tests__/index.test'>;
}
declare module '@fullhuman/postcss-purgecss/jest.config.js' {
  declare module.exports: $Exports<'@fullhuman/postcss-purgecss/jest.config'>;
}
declare module '@fullhuman/postcss-purgecss/lib/postcss-purgecss.es.js' {
  declare module.exports: $Exports<'@fullhuman/postcss-purgecss/lib/postcss-purgecss.es'>;
}
declare module '@fullhuman/postcss-purgecss/lib/postcss-purgecss.js' {
  declare module.exports: $Exports<'@fullhuman/postcss-purgecss/lib/postcss-purgecss'>;
}
declare module '@fullhuman/postcss-purgecss/rollup.config.js' {
  declare module.exports: $Exports<'@fullhuman/postcss-purgecss/rollup.config'>;
}
declare module '@fullhuman/postcss-purgecss/src/index.js' {
  declare module.exports: $Exports<'@fullhuman/postcss-purgecss/src/index'>;
}
